version: 2
jobs:
  build:
    working_directory: ~/blog
    docker:
      - image: circleci/ruby:2.5.1
    steps:
      - checkout
      - run: gem install bundler
      - run:
          name: Running bundle install
          command: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs=4 --retry=3
      - run:
          name: Making build
          command: jekyll build
      - deploy:
          name: Uploading staging build to Amazon S3
          command: |
            aws s3 sync --delete ./build s3://jquintanab.com --region eu-west-2
workflows:
    version: 2
    build_and_deploy:
      jobs:
        - build:
            filters:
              branches:
                only:
                  - master
